dist: trusty
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
script:
  - travis/build.sh
