dist: trusty
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
script:
- sqlite3 -version
- python manage.py test
- python manage.py sync_from_webservice
- python manage.py update_affair_details --parallel 12
